import type { Metadata } from 'next';
import { PropsWithChildren } from 'react';
import '@with/foundation/themes.css';
import '@with/foundation/globalStyle.css';
import '@with/services/style.css';

export const metadata: Metadata = {
	title: 'Create Turborepo',
	description: 'Generated by create turbo',
};

const RootLayout = ({ children }: PropsWithChildren) => {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
};

export default RootLayout;
